### PR TITLE
add Dockerfile to run aboutcode with docker

### PR DESCRIPTION
**Pull request by ddmesh**
Analog to scancode I have created a **Dockerfile**, so aboutcode can be run via docker.

### CODE REVIEW

**Comment by pombredanne** [comment]
Thank you ++

**Review by pombredanne — APPROVED** [review]
Neat and clean. LGTM. Ready to merge.

**Comment by ddmesh** [comment]
hi, any idea when this merge request will be merged? hope soon ☺️

**Comment by chinyeungli** [comment]
Thanks and sorry for the delay.

**Pull request merged**
