### PR TITLE
added blank after header-2

### PR DESCRIPTION
**Pull request by hesa**

### CODE REVIEW

**Comment by pombredanne** [comment]
Thanks! I will not bug you with a DCO one for one space :D

**Comment by hesa** [comment]
But, on the other hand, I think it is a very powerful space... so I figure it ought to be copyrightable

**Comment by pombredanne** [comment]
@hesa that's fair enough. Do you mind to register this space with your neighborhood copyright office first? Just to make sure nobody else claimed it first.

**Comment by GABBER202025** [comment]
docs/UsingAboutCodetoDocumentYourSoftwareAssets.md

**Pull request merged**
